apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: c18nuga45-java-quarkus-gitops-repository
spec:
  url: https://github.com/chetna14manku-org/c18nuga45-java-quarkus-gitops